### ISSUE TITLE
[FR] Built in Cloudflare email decoding converter

### ISSUE THREAD

**Issue by HelgeSverre** [crwlrsoft/html-2-text#1]
It would be neat if we this package could include certain "decoders" for common annoyances you'll occur when crawling the web, might take a crack at a PR for this later, but for now i'll just leave the reference implementation I made for my app incase anyone needs it asap.

```
<?php

namespace App\Crawling\Converters;

use Crwlr\Html2Text\Aggregates\DomNodeAndPrecedingText;
use Crwlr\Html2Text\NodeConverters\LinkConverter;

class CloudflareEmailDecoder extends LinkConverter
{
    public function convert(DomNodeAndPrecedingText $node): string
    {
        $domNode = $node->node;
        $href = $domNode->getAttribute('href');

        if (strpos($href, '/cdn-cgi/l/email-protection') !== false) {
            $encodedEmail = str_replace('/cdn-cgi/l/email-protection#', '', $href);
            $decodedEmail = $this->decodeCloudflareEmail($encodedEmail);

            return $decodedEmail;
        }

        // If it's not an encoded email link, just return the original text
        return parent::convert($node);
    }

    protected function decodeCloudflareEmail(string $encodedEmail): string
    {
        $key = hexdec(substr($encodedEmail, 0, 2));
        $decodedEmail = '';

        for ($i = 2, $len = strlen($encodedEmail); $i < $len; $i += 2) {
            $decodedEmail .= chr(hexdec(substr($encodedEmail, $i, 2)) ^ $key);
        }

        return $decodedEmail;
    }
}
```

**Comment by otsch** [comment]
Hey @HelgeSverre,
really cool to see you're already building your own converters! Awesome!

I just had a look at the kind of links that your converter is targeting. I have to say I'm sorry, but I'd rather not include this in the package, for several reasons:
* This email obfuscation is built to protect email adresses from being harvested by spambots. The crwlr libraries are designed to be polite and respect such security measures, even though this kind is typically very weak 😬😅 and I understand the argument that it's just about data (emails) that actually are publicly visible on a web page.
* I guess there's a myriad of such obfuscations out there and I don't want to bloat the package by trying to solve all of them.
* Also because I bet they'll probably change the way they work from time to time and then you'll have to also adapt your solution. I don't want to take part in that arms race.
* There's also a very easy solution to get those email adresses (that I won't publish here 😉😅) without actually targeting this special obfuscation method and having to adapt it after a change.

I hope you'll understand this.

**Comment by HelgeSverre** [comment]
Fair enough :D
